- hosts: localhost

  vars:

    error: {"msg": "The task includes an option with an undefined
    variable. The error was: 'dict object' has no attribute
    'matched'\n\nThe error appears to be in
    '/home/a239255/testing/test-playbook/restart-test3.yml': line 10,
    column 13, but may\nbe elsewhere in the file depending on the
    exact syntax problem.\n\nThe offending line appears to be:\n\n
    register: extracted\n - debug:\n ^ here\n"}
    
    # Search for this "nodeagent stopped" in a file
    matched: "{{ file_log.content|b64decode|split('\n')|
                 select('search', 'nodeagent stopped') }}"

  tasks:

#    - name: extract a word
#      ansible.builtin.lineinfile:
#        path: /file/to/path/file.log
#        regexp: '^nodeagent stopped: (.*)'
#        line: 'nodeagent stopped'
#      register: extracted
#    - debug:
#        msg: 'The extracted word is {{ extracted.matched }}'
    - debug:
        var: error

    - name: Read the file
      ansible.builtin.slurp:
        src: /tmp/file.log
      register: file_log

    - debug:
        var: file_log.content|b64decode

    - debug:
        var: matched
